FROM golang:1.25.1 AS builder

WORKDIR /app
COPY . .

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api

# Imagen final
FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/api .
COPY dataset ./dataset

EXPOSE 8080

CMD ["./api"]
