version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
      - node1
      - node2
      - node3
    environment:
      # CRÍTICO: Aquí definimos los 3 nodos usando sus nombres de servicio docker
      # El puerto debe coincidir con el puerto interno del contenedor (INTERNAL_PORT)
      - WORKER_NODES=node1:9001,node2:9002,node3:9003
      - REDIS_ADDR=redis:6379
      - MONGO_ADDR=mongodb://mongo:27017
      # Asegúrate de que esta ruta exista DENTRO del contenedor
      - DATASET_PATH=/app/dataset/10M 

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    hostname: node1
    # Sobrescribimos el comando para asegurar que escuche en el puerto correcto
    # Asumiendo que tu main.go del nodo acepta argumentos: ./node [dataset] [puerto]
    command: ["./node", "10", "9001"] 
    ports:
      - "9001:9001"

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    hostname: node2
    command: ["./node", "10", "9002"]
    ports:
      - "9002:9002"

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node
    hostname: node3
    command: ["./node", "10", "9003"]
    ports:
      - "9003:9003"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
